# Basic
name:               "Computational Auditory Perception Lab"
title:              ""
description:        "A research laboratory."


# URL
url:                https://music-cognition-lab.github.io
baseurl:            
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publications"
  - name:           "projects"
    href:           "/projects"
  - name:           "seminars"
    href:           "/seminars"
  - name:           "events"
    href:           "/events"
  - name:           "resources"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
